/**
 * Transcript of the full AFAB Services interview on Mux (the 6:06 cut), split
 * into speaker turns. `t` is seconds into that video. Generated from the audio
 * with speech recognition, with filler words removed and misheard words
 * corrected by hand.
 */
import type { TranscriptTurn } from "@/lib/video-case-study";

export const AFAB_INTERVIEW_TRANSCRIPT: TranscriptTurn[] = [
  { t: 0, speaker: "Jacob", text: "How has your experience been with us so far?" },
  { t: 2, speaker: "Mark", text: "It's been good, it's been good. First couple of weeks, we're going to work out glitches, and things happen. It is what it is. You're getting a feel for me. Again, I'm not just an epoxy guy. I'm out here hanging doors in a commercial environment for a place called the Back Nine. I work for a commercial builder as well. I constantly stay busy, man. There's homes too. You name it, I do it. I'm at it seven days a week. The bread and butter is my remodeling business, but like I've spoken with you, I really, really am trying to push the epoxy more. I did get the pool deck. Yesterday went pretty good with that lady. There's a couple other things she wants to do with her house. I'm like, look, I'm your one-stop shop. Let's do your floor, I can close in your lanai. So it is what it is. But as far as working with you and your company, I'm satisfied." },
  { t: 63, speaker: "Jacob", text: "It sounds like you can get a foot in the door with these people. You never know what they're going to want in the future as well." },
  { t: 69, speaker: "Mark", text: "That's exactly true. I get my foot in the door, give her my card, say, look me up online, look up my company, AFAB Services, BBB approved, then I put in my other spiel. So I'm your one-stop shop. A lot of people like that don't want half a dozen people traipsing in and out of their house." },
  { t: 88, speaker: "Jacob", text: "Fantastic. And then the other question would be, a lot of people that I speak to have maybe never worked with a company like mine, or they don't know what it's going to be like. What would you say your experience was like as soon as an appointment is booked?" },
  { t: 101, speaker: "Mark", text: "It's pretty straightforward. Here's the deal. You've already kind of paved the ground. I just go on in and sweep it up, basically. I wasn't sure what to expect, but I'm happy and I'm satisfied. Overall, it's a good experience. Yes, sir." },
  { t: 120, speaker: "Jacob", text: "Okay, fantastic. Touching on what you just said, what did you expect going in versus what turned out to be different?" },
  { t: 128, speaker: "Mark", text: "Pretty much what I expected is what I'm being delivered. And I like the idea that you vet the people. You make sure that they're not just kicking tires, because time is money, whether it's yours or mine. Both of our time is money. You're setting leads for me, I'm paying you to do that, and I'm appreciative that you're making sure that they're financially able, that they're not tire kicking, because it costs me money to go out and meet these people. So I appreciate that you're vetting them. You're doing your due diligence." },
  { t: 168, speaker: "Jacob", text: "Exactly. At the end of the day, you might see that I book an appointment for you, but what you don't see is the two to three people that I spoke to on the phone that I decided it's not worth putting onto your calendar for now." },
  { t: 179, speaker: "Mark", text: "And that I very much appreciate. Because I think I had said I was working with a company before, and I would have 30 different things a week, but maybe two of them were legit. And of those two, I was lucky if I got one, because I'm not the only company out there booking it." },
  { t: 199, speaker: "Jacob", text: "And with those, you had to call them yourself, right?" },
  { t: 201, speaker: "Mark", text: "I had to call them myself, set it all up. Yes. Which takes time out of my day as well. I'm out here 13, 14 hours a day as it is. So that works well for me, that you're just saying, hey, this is the time, can you make it at this time? And I make a yes or no. So it's working out well." },
  { t: 225, speaker: "Jacob", text: "And then in terms of getting started, I emphasized that it might take a while to ramp up. I think the first appointment that we set for you, you actually closed, right?" },
  { t: 235, speaker: "Mark", text: "It was the second appointment. I did close that, yes. And with that, they have a whole bunch of remodeling stuff inside that they want to do, the 7 1/4 inch baseboards, all of that. So not only am I getting your lead for the epoxy, I'm also going to get more work out of it on the remodeling end. So it's a win-win for me." },
  { t: 261, speaker: "Jacob", text: "Exactly, that's what it's all about. Front end, I'm on the phone all day, I book them in, you handle your side of the agreement. Okay, last question, because I speak with a lot of folks, and as you can imagine, kind of what you just mentioned, there's a lot of people that don't do a good job when it comes to generating leads or getting appointments. So when I speak to folks, a lot of them are skeptical. They might think, is it going to work for me? What would you say to them?" },
  { t: 290, speaker: "Mark", text: "Being skeptical goes with the territory. It's understandable. Nothing ventured, nothing gained. I wasn't sure whether I wanted to do it or not, but I jumped into the deep end of the pool and I'm happy I'm swimming. So yeah, take a leap of faith. I've had lead generation companies before and they did not pan out. You guys are doing a great job." },
  { t: 317, speaker: "Jacob", text: "And then final question, what's been the difference between paying for leads themselves versus with appointments?" },
  { t: 323, speaker: "Mark", text: "Paying for leads themselves is working out better because, again, you are vetting the people. You are making sure that the lead is qualified and they are ready to pull the trigger to do whatever epoxy project it is that they're wanting. So paying per lead is working out well, because of the five clicks that you might get on the Facebook ad, or wherever you are advertising for my company, out of those five clicks, maybe one is a solid lead for me. So instead of just paying per click or whatever, if that's the right terminology, paying per lead is working out great." },
];
