/**
 * Transcript of the full Garage Force of the Inland Northwest interview on Mux
 * (the 10:20 cut), split into speaker turns. `t` is seconds into that video.
 * Generated from the audio with speech recognition, with filler words removed
 * and misheard words corrected by hand. Eric and Shani were told apart by
 * voice; Shani answers the closing question.
 */
import type { TranscriptTurn } from "@/lib/video-case-study";

export const GF_INTERVIEW_TRANSCRIPT: TranscriptTurn[] = [
  { t: 0, speaker: "Jacob", text: "Okay, so Eric and Shani, we've been working together for, how long has it been?" },
  { t: 6, speaker: "Shani", text: "Two months? A couple months, yeah." },
  { t: 9, speaker: "Jacob", text: "Checking how many appointments we've gotten you guys, out of the ones that showed up, which has been pretty much all of them, I think we're at 31 appointments so far. And you guys are in a unique situation as well, because you're a little bit more upmarket, premium positioning. You tend to charge a little bit more for your services than the nationwide companies, or even than your competitors, right? So when you came to me, we had essentially two problems, if you would agree. One was the volume: you weren't getting enough appointments coming in. And two, you didn't want to create another problem by making the appointments that do come in low quality, or people that can't afford you. So talk me through what it was like before working with us in terms of volume, and then afterwards, with your calendar being a little more consistent." },
  { t: 57, speaker: "Eric", text: "Yeah, we weren't getting enough volume, like you said. We weren't going on enough appointments, and the ones we were going on, we were basically wasting our time, spending hours to go on a bid that wasn't qualified. So the prequalification that you're doing for us is amazing." },
  { t: 75, speaker: "Jacob", text: "Before you worked with us, what was the volume like? I know you were still getting appointments here or there, but what was it like on your end?" },
  { t: 83, speaker: "Eric", text: "It was really hit or miss. Being that we're a newer business, we were learning how to do it also, but we were getting business from trade shows, which was hit or miss, because you don't have a lot of trade shows and they're expensive. We were getting volume from sending things like postcards and paper ads in the mail, and honestly, they were very, very price conscious. We were getting smaller jobs in less than desirable areas." },
  { t: 112, speaker: "Jacob", text: "Okay, got it. That's typically exactly what happens before somebody has a steady stream of qualified appointments coming through. We wanted to make sure we were going after a specific type of appointment, and obviously we're still dialing that in even more. But how would you rate the quality so far? Sometimes you hear about Facebook leads or Instagram leads, and you don't know what the quality is going to be like. What has it been like working with us so far?" },
  { t: 141, speaker: "Eric", text: "It's been great. The refining that we're doing is going to make it A plus, and we're getting there." },
  { t: 149, speaker: "Jacob", text: "What do you mean by refining, for the audience at home?" },
  { t: 154, speaker: "Eric", text: "Figuring out what leads we should go out on. Is it indoor or outdoor? Is it people that are tire kicking, or are they truly serious about buying? As we get better at that, we're seeing the better leads come in now." },
  { t: 169, speaker: "Jacob", text: "Yep, 100%. And the biggest thing I would add to that is that with a lot of companies like mine, you can get similar volume, but they might not be as personal or as focused on getting you what you want, because they're fulfilling their end of it technically: hey, I sent you 40 leads, here's 40 names and numbers for the month. A lot of companies can do that. Talk to me about the partnership we've had together. What's it been like working with me specifically?" },
  { t: 204, speaker: "Eric", text: "It's like our business, where we're selling ourselves. We're on every job site. We don't want 50, 100 leads every week. That's going to overwhelm us, we're wasting our time. We're a very hands-on, mom and pop kind of business, and you're treating us the same way. We're understanding each other, we're understanding what we want, what works best. We get called every day from those other companies, literally every day: we'll give you 50 leads, we'll give you 100 leads. And yes, they're charging less for those leads, but we know without a doubt they're not quality leads." },
  { t: 240, speaker: "Jacob", text: "Yes. That's good that you know that, because it can be confusing for business owners. Like you said, everybody has an offer for you, everyone has a spiel for you, and the truth, being in the industry for a while now, is that they're trying to do the least amount of work for the most personal gain. Their main interest is just technically doing their job, sending you a bunch of leads. But there's a difference between a lead and an appointment, and then a difference between an appointment and a qualified appointment. So for you, what makes an appointment qualified, and what are the best kind of appointments that you've been getting?" },
  { t: 276, speaker: "Eric", text: "They understand at least a little bit about the product and how we differentiate. We have a higher quality product. Yes, the price point might be a little higher, but they're willing to spend that money to have things like a lifetime warranty, and have us on the job site, not just the typical manual laborers going out to get a job done as fast as they can." },
  { t: 300, speaker: "Jacob", text: "Fantastic. Out of the appointments you've closed so far with us, or the ones you'll probably close in the next few weeks, what have they been like? And how many do you feel like you've closed so far?" },
  { t: 313, speaker: "Eric", text: "I think we've closed six, guaranteed, paid deposits. We probably have another four or five more that are going to close at some point, and then the others, we may win some of them. But the ones we've closed, and that we think we're going to close, have been very high quality. They're typically a little bit older, probably 40 to 60, 70 years old. They understand quality. They value having people in their home that aren't going to steal their things. It's a more discerning customer." },
  { t: 353, speaker: "Jacob", text: "Got it. That makes a lot of sense. With any business owner, but especially with the two of you, you have a very busy schedule, a very intense business with a lot going on. What's it been like working with someone who can handle the scheduling, appointment setting and qualifying side of the equation?" },
  { t: 375, speaker: "Eric", text: "It's been great. The one on one communication. You're kind of like us, and you're not a business that has eight to five hours. We're communicating in the morning, at night, on the weekends. It's very one on one, very hands on, and we appreciate that." },
  { t: 393, speaker: "Jacob", text: "Okay, last question, just to wrap it up. Where were you before starting with me, in terms of what made you nervous about getting started with a company like mine? And what were some of the misconceptions that cleared up over time as we got started?" },
  { t: 411, speaker: "Eric", text: "It's like any small business: is the cost worth it, or are we going to get the results? It's taken us a couple of weeks, probably a month and a half, to really start dialing it in. But once we're dialed in, we feel like it's going to be great long term." },
  { t: 427, speaker: "Jacob", text: "And what would you tell someone who's telling me, hey Jacob, look, I can see the sense in what you're saying. I can see the results you're getting, and I can see this working for a lot of companies pretty similar to mine. But with the cost, I'm scared to put a thousand and a half, two thousand dollars into advertising. I'm just not sure if I'm going to get the return." },
  { t: 451, speaker: "Eric", text: "Yeah, that's a tough call as a business owner. You have to see the results, and again, we're continuing to get better. I don't want to say this negatively, but if you're just looking for as many small, cheap jobs as you can get, maybe it's not a fit. If you're looking for quality, pre-qualified leads, then it's absolutely worth the spend." },
  { t: 480, speaker: "Jacob", text: "100%, I totally agree. There are other options on the market, and they do seem appealing at first glance because it's less money. It seems like you're paying less. But a lot of those companies don't make you any kind of guarantee or have any vested interest in your business. You sign up with them, you pay the money, and that's it. There's no further investigation into the quality at that point. Versus with us, at least on my end, if I'm getting you an appointment, I want it to be qualified. I don't want you to pay for stuff that's not qualified. Can you attest to that, quality versus quantity?" },
  { t: 526, speaker: "Eric", text: "Yeah, the conversations we have, the back and forth of this was good, this wasn't, and you're willing to credit stuff back that just turned out to not be a fit. And again, back to the refining of this process: as we go forward, we're probably not going to ask you to refund us very many at all, because we've gotten so good at qualifying and sending us on the right jobs." },
  { t: 548, speaker: "Jacob", text: "Exactly. Shani, anything to add? Closing thoughts?" },
  { t: 552, speaker: "Shani", text: "Yeah, I do want to say, we don't ask every single person, but we do ask people when we go out on these bids how they felt about the setup and speaking with you, and we've gotten very positive feedback. The people that you talk to appreciate what you've said and what you've done, and they seem to like you and like the service. That was a concern for us as a small business: do we want a third party out there fielding our leads and scheduling our bids? And it's been great for us and for our customers. We're very happy." },
  { t: 588, speaker: "Jacob", text: "That's awesome. I love that you said that, because there are a lot of businesses out there, and you guys aren't at this point, that have an office manager or somebody like that, and to be perfectly honest, they can't do what we do in terms of booking the number of appointments we book and qualifying folks over the phone, because their whole job is customer service, being friendly. Our whole job is making sure we're not wasting your time, and booking the most positive at-bats that we can. So thank you for saying that." },
];
